workflows:
  build_web:
    name: Build Subscription Tracker (Web)
    max_build_duration: 30
    instance_type: linux
    environment:
      node: 20
      npm: latest
      vars:
        BUILD_DIR: "dist"
    scripts:
      - name: Install dependencies
        script: npm install
      - name: Build project
        script: npm run build
      - name: List build output
        script: ls -la $BUILD_DIR
    artifacts:
      - $BUILD_DIR/**
