workflows:
  build_and_deploy_vercel:
    name: Build & Deploy (Vercel)
    max_build_duration: 60
    instance_type: e1-standard-2
    environment:
      node: 20
      npm: latest
      vars:
        BUILD_DIR: "dist"
    scripts:
      - name: Install dependencies
        script: npm ci
      - name: Build project
        script: npm run build
      - name: Install Vercel CLI
        script: npm install -g vercel
      - name: Vercel deploy (production)
        script: vercel deploy --prod --confirm --token $VERCEL_TOKEN --cwd $BUILD_DIR
    artifacts:
      - $BUILD_DIR/**
